#server:
#  port: 8081
#  servlet:
#    context-path: /
#  tomcat:
#    uri-encoding: UTF-8
#    threads:
#      max: 1000
#      min-spare: 30
#    max-swallow-size: -1
#  shutdown: graceful
#spring:
#  datasource:
#    url: jdbc:mysql://:21797/hrms_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
#    username: root
#    password: Liuyp123456@
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#      filter:
#        wall:
#          config:
#            multi-statement-allow: true
#    hikari:
#      max-lifetime: 60000
#      maximum-pool-size: 1000
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  servlet:
#    multipart:
#      max-file-size: 10240MB
#      max-request-size: 10240MB
#  jackson:
#    time-zone: GMT+8
#    serialization:
#      fail-on-empty-beans: false
#  data:
#    redis:
#      host:  127.0.0.1 #121.4.35.186
#      database: 0
#      timeout: 3S
#      port: 6379
#      password: 123456
#intercept:
#  verification:
#    - /zwz/login
#    - /zwz/user/regist
#  wechat:
#    - /zwz/user/smsLogin
#    - /zwz/user/resetByMobile
#    - /zwz/user/changeMobile
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    root: info
#  file:
#    path: logs
#  logback:
#    rollingpolicy:
#      max-history: 2000
#      max-file-size: 5MB
server:
  port: 8081
  servlet:
    context-path: /api/v1
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-swallow-size: -1
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://121.4.35.186:3306/hrms_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: mysql_8jBre4
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  data:
    redis:
      host:  121.4.35.186 #121.4.35.186
      database: 0
      timeout: 3S
      port: 6379
      password: 123456
intercept:
  verification:
    - /api/v1/auth/login
    - /api/v1/users/register
  wechat:
    - /api/v1/users/sms-login
    - /api/v1/users/reset-password
    - /api/v1/users/change-mobile
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 2000
      max-file-size: 5MB